
#!/bin/bash




PATH_TO_ALL_VIDEOS_INFO="data_info/all_videos.txt"
PATH_TO_VIDEOS_TRAIN_LIST="data_info/trainPart0.txt"
PATH_TO_VIDEOS_TEST_LIST="data_info/testPart0.txt"
PATH_TO_CLASS_LIST="data_info/classInd.txt"

PATH_TO_FEATURES="./HOG_FEA/"
OUTPUT_TRAIN_PATH="./HOG_NPY/train_per_class"
OUTPUT_TEST_PATH="./HOG_NPY/test_per_class"

N_FEATURES=500

#python fea2numpy.py $PATH_TO_ALL_VIDEOS_INFO $PATH_TO_VIDEOS_TRAIN_LIST $PATH_TO_CLASS_LIST $PATH_TO_FEATURES $N_FEATURES $OUTPUT_TRAIN_PATH
python fea2numpy.py $PATH_TO_ALL_VIDEOS_INFO $PATH_TO_VIDEOS_TEST_LIST  $PATH_TO_CLASS_LIST $PATH_TO_FEATURES $N_FEATURES $OUTPUT_TEST_PATH

